# Generated by Django 3.1.3 on 2021-01-25 15:10

from django.db import migrations, models
import web.multilingual.database


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', web.multilingual.database.MultiLingualTextField(unique=True, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', web.multilingual.database.MultiLingualTextField(unique=True, verbose_name='Question')),
                ('answer', web.multilingual.database.MultiLingualRichTextUploadingField(verbose_name='Answer')),
                ('categories', models.ManyToManyField(related_name='questions', to='faq.Category')),
            ],
        ),
    ]
