# Generated by Django 3.0.10 on 2020-10-20 13:27

from django.db import migrations, models
import web.multilingual.database


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', web.multilingual.database.MultiLingualTextField(max_length=255, unique=True, verbose_name='Question')),
                ('answer', web.multilingual.database.MultiLingualRichTextUploadingField(verbose_name='Answer')),
                ('categories', models.ManyToManyField(related_name='questions', to='faq.Category')),
            ],
        ),
    ]
