---
name: "Install dependencies"
description: "Sets up Python and uv and installs all dependencies."

inputs:
  uv-sync-extra-args:
    description: "Extra arguments to pass to the `uv sync` command."
    required: false
    default: ""

runs:
  using: "composite"
  # Code based on https://docs.astral.sh/uv/guides/integration/github/
  steps:
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version-file: "pyproject.toml"

    - name: Install System Dependencies
      shell: bash
      # Retries installing files 3 times, as either the GitHub Actions runner or APT's API can be unreliable
      run: |
        sudo apt update
        sudo apt install python3-dev libldap2-dev libsasl2-dev libssl-dev -o Acquire::Retries=3

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true

    - name: Set `UV_PROJECT_ENVIRONMENT` envvar
      shell: bash
      # Install packages into the system environment instead of a `.venv/`.
      # (`pythonLocation` is from `actions/setup-python` - see
      # https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#environment-variables)
      run: echo "UV_PROJECT_ENVIRONMENT=$pythonLocation" >> $GITHUB_ENV
    - name: Install Python dependencies
      shell: bash
      run: uv sync --locked ${{ inputs.uv-sync-extra-args }}
