coverage:
  status:
    project:
      default:
        threshold: 80%
    patch:
      default:
        threshold: 80%

ignore:
  - "manage.py"
  - "src/web/settings.py"
  - "src/**/apps.py"
  - "src/**/wsgi.py"
  - "src/**/asgi.py"
  - "src/**/test*.py"
  - "src/**/*test.py"
  - "src/**/migrations/**"
  - "src/**/__init__.py"
