coverage:
  range: "75..90"
  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default:
        target: 80%
        threshold: 30%

codecov:
  require_ci_to_pass: false

comment:
  layout: "reach, diff, files"
  behavior: default
  require_changes: false

ignore:
  - "manage.py"
  - "src/web/settings.py"
  - "src/**/apps.py"
  - "src/**/wsgi.py"
  - "src/**/asgi.py"
  - "src/**/test*.py"
  - "src/**/migrations/**"
