---
coverage:
  range: "75..90"
  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default:
        target: 80%
        threshold: 30%

codecov:
  require_ci_to_pass: false

comment:
  layout: "reach, diff, files"
  behavior: default
  require_changes: false
  # Codecov occasionally does not post a comment on PRs for some reason; the two lines
  # below force Codecov to always post a comment (see
  # https://docs.codecov.com/docs/pull-request-comments#requiring-the-base-andor-head-commit)
  # (They can be removed if the above stops happening)
  require_head: false
  require_base: false

ignore:
  - "manage.py"
  - "src/web/wsgi.py"
  - "src/web/asgi.py"
  - "src/web/settings.py"
  - "src/**/tests/**"
  - "src/**/migrations/**"
