version: '3'

services:
  web:
    build: .
    command: >
      bash -c "uv run manage.py migrate
      && uv run manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/web
    ports:
      - "8000:8000"
    env_file:
      - .env
