version: '3'
    
services:
  web:
    build: .
    command: >
        bash -c "python manage.py migrate
        && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/web
    ports:
      - "8000:8000"
