# Generated by Django 2.0.2 on 2018-09-06 17:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checkin", "0004_auto_20180906_1855"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="suggestskill",
            name="approved",
        ),
    ]
