# Generated by Django 5.0.2 on 2026-03-10 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0012_profile_user_non_nullable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suggestskill',
            options={'ordering': ('title',), 'permissions': [('can_force_suggestion', 'Can force suggestion')]},
        ),
    ]
