# Generated by Django 2.0.1 on 2018-02-14 12:54

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tittel')),
                ('content', ckeditor.fields.RichTextField()),
                ('clickbait', models.TextField(blank=True, max_length=300, verbose_name='Clickbait')),
                ('image', models.ImageField(upload_to='', verbose_name='Bilde')),
                ('contain', models.BooleanField(default=False, verbose_name='Ikke crop bildet')),
                ('featured', models.BooleanField(default=False, verbose_name='Fremhevet')),
                ('hidden', models.BooleanField(default=False, verbose_name='Skjult')),
                ('private', models.BooleanField(default=False, verbose_name='MAKE intern')),
            ],
        ),
        migrations.CreateModel(
            name='TimePlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(default=django.utils.timezone.now, verbose_name='Publiseringsdato')),
                ('pub_time', models.TimeField(default=datetime.time(0, 0), verbose_name='Publiseringstid')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Start-dato')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Slutt-dato')),
                ('start_time', models.TimeField(default=datetime.time(0, 0), verbose_name='Start-tidspunkt')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Slutt-tidspunkt')),
                ('place', models.CharField(blank=True, max_length=100, verbose_name='Sted')),
                ('place_url', models.CharField(blank=True, max_length=200, verbose_name='Sted URL')),
                ('hoopla', models.CharField(blank=True, max_length=200, verbose_name='Hoopla url')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('newsbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.NewsBase')),
                ('pub_date', models.DateField(default=django.utils.timezone.now, verbose_name='Publiseringsdato')),
                ('pub_time', models.TimeField(default=datetime.time(0, 0), verbose_name='Publiseringstid')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
            bases=('news.newsbase',),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('newsbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.NewsBase')),
            ],
            bases=('news.newsbase',),
        ),
        migrations.AddField(
            model_name='timeplace',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Event'),
        ),
    ]
