# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 05:31
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tittel')),
                ('content', ckeditor.fields.RichTextField()),
                ('clickbait', models.TextField(blank=True, max_length=300, verbose_name='Clickbait')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Bilde')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Opprettelsesdato')),
                ('hidden', models.BooleanField(default=False, verbose_name='Skjult')),
                ('private', models.BooleanField(default=False, verbose_name='Privat')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.Article')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start-tidspunkt')),
                ('end_time', models.DateTimeField(blank=True, verbose_name='Slutt-tidspunkt')),
                ('place', models.CharField(blank=True, max_length=100, verbose_name='Sted')),
                ('place_url', models.CharField(blank=True, max_length=200, verbose_name='Sted URL')),
                ('hoopla', models.CharField(blank=True, max_length=200, verbose_name='Hoopla url')),
            ],
            bases=('news.article',),
        ),
    ]
