# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180111_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='contain',
            field=models.BooleanField(default=True, verbose_name='Ikke crop bildet'),
        ),
    ]
