# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_contain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contain',
            field=models.BooleanField(default=False, verbose_name='Ikke crop bildet'),
        ),
    ]
