# Generated by Django 2.0.4 on 2018-04-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20180308_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsbase',
            name='featured',
            field=models.BooleanField(default=True, verbose_name='Fremhevet'),
        ),
    ]
