# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20180119_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Bilde'),
        ),
    ]
