# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20180119_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Publiseringsdato'),
        ),
    ]
