# Generated by Django 2.0.1 on 2018-03-06 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_article_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('start_date',)},
        ),
    ]
