# Generated by Django 2.1.2 on 2018-12-08 15:16

from django.db import migrations
import web.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20181013_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsbase',
            name='clickbait',
            field=web.fields.MultiLingualTextField(blank=True, max_length=300, verbose_name='Clickbait'),
        ),
        migrations.AlterField(
            model_name='newsbase',
            name='title',
            field=web.fields.MultiLingualTextField(max_length=100, verbose_name='Title'),
        ),
    ]
