# Generated by Django 2.1.5 on 2019-01-27 11:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0011_auto_20181209_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTicket',
            fields=[
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('language', models.CharField(choices=[('en', 'English'), ('nb', 'Norwegian')], default='en', max_length=2, verbose_name='Preferred language')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'permissions': (('cancel_ticket', 'Can cancel and reactivate all event tickets'),),
            },
        ),
        migrations.AddField(
            model_name='event',
            name='number_of_tickets',
            field=models.IntegerField(default=0, verbose_name='Number of available tickets'),
        ),
        migrations.AddField(
            model_name='timeplace',
            name='number_of_tickets',
            field=models.IntegerField(default=0, verbose_name='Number of available tickets'),
        ),
        migrations.AlterField(
            model_name='timeplace',
            name='end_time',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='End time'),
        ),
        migrations.AddField(
            model_name='eventticket',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Event', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='eventticket',
            name='timeplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.TimePlace', verbose_name='Timeplace'),
        ),
        migrations.AddField(
            model_name='eventticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
