# Generated by Django 2.1.2 on 2019-01-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_eventticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventticket',
            name='event',
            field=models.ManyToManyField(to='news.TimePlace'),
        ),
    ]
