# Generated by Django 2.1.2 on 2019-01-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_eventticket_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='number_of_tickets',
            field=models.IntegerField(default=0, verbose_name='Number of available tickets'),
        ),
        migrations.AddField(
            model_name='timeplace',
            name='number_of_tickets',
            field=models.IntegerField(default=0, verbose_name='Number of available tickets'),
        ),
    ]
