# Generated by Django 2.1.5 on 2019-02-23 00:43

from django.db import migrations, models


def event_type_from_multiday(apps, schema_editor):
    Event = apps.get_model("news", "Event")
    for event in Event.objects.all():
        event.event_type = "S" if event.multiday else "R"
        event.save()


def reverse_event_type_from_multiday(apps, schema_editor):
    Event = apps.get_model("news", "Event")
    for event in Event.objects.all():
        event.multiday = event.event_type == "S"
        event.save()


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0013_remove_hoopla'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('R', 'Repeating'), ('S', 'Standalone')], default='R', max_length=1, verbose_name='Type of event'),
        ),
        migrations.RunPython(event_type_from_multiday, reverse_event_type_from_multiday),
        migrations.RemoveField(
            model_name='event',
            name='multiday',
        ),
    ]
