# Generated by Django 2.1.5 on 2019-01-18 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20190118_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventticket',
            name='timeplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.TimePlace', verbose_name='Timeplace'),
        ),
        migrations.RemoveField(
            model_name='eventticket',
            name='event',
        ),
        migrations.AddField(
            model_name='eventticket',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Event', verbose_name='Event'),
        ),
    ]
