# Generated by Django 2.1.5 on 2019-02-23 12:16

from django.db import migrations
import web.multilingual.database


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsbase',
            name='clickbait',
            field=web.multilingual.database.MultiLingualTextField(max_length=300, verbose_name='Clickbait'),
        ),
    ]
