# Generated by Django 2.1.5 on 2019-01-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20190118_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventticket',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='eventticket',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comment'),
        ),
    ]
