# Generated by Django 2.1.5 on 2019-01-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20190118_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventticket',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('nb', 'Norwegian')], default='en', max_length=2),
        ),
    ]
