# Generated by Django 2.1.5 on 2019-01-18 14:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_eventticket_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventticket',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='eventticket',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('nb', 'Norwegian')], default='en', max_length=2, verbose_name='Preferred language'),
        ),
    ]
