# Generated by Django 2.1.5 on 2019-01-18 14:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_auto_20190118_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventticket',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
