# Generated by Django 3.1.6 on 2021-02-15 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_use_datetime_instead_of_date_and_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeplace',
            options={'ordering': ('start_time',), 'permissions': (('can_send_email', 'Can send email'),)},
        ),
    ]
