# Generated by Django 2.1.5 on 2019-01-18 14:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_auto_20190118_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventticket',
            name='id',
        ),
        migrations.AlterField(
            model_name='eventticket',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
