# Generated by Django 2.1.5 on 2019-01-26 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_auto_20190118_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventticket',
            options={'permissions': (('cancel_ticket', 'Can cancel and reactivate all event tickets'),)},
        ),
    ]
