# Generated by Django 3.1.6 on 2021-04-19 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_add_related_names'),
        ('news', '0018_send_email_permission'),
    ]

    operations = [
    ]
