# Generated by Django 3.1.6 on 2021-04-20 12:10

from django.db import migrations, models
import web.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_empty.py'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=60, verbose_name='Subject')),
                ('body', models.TextField(verbose_name='Body')),
                ('recipients', web.modelfields.UnlimitedCharField(verbose_name='Recipients')),
            ],
        ),
        migrations.AlterModelOptions(
            name='timeplace',
            options={'ordering': ('start_time',)},
        ),
    ]
