# Generated by Django 2.0.1 on 2018-04-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("make_queue", "0002_auto_20180408_1018"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="stream_url",
            field=models.URLField(default=""),
        ),
    ]
