# Generated by Django 3.0.5 on 2020-09-13 01:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("make_queue", "0017_remove_fields_max_length_and_add_blank"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="showed",
        ),
    ]
