# Generated by Django 3.1.2 on 2020-11-04 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_auto_20180307_1352"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("make_queue", "0018_remove_reservation_showed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="printer3dcourse",
            options={
                "verbose_name": "3D printer course",
                "verbose_name_plural": "3D printer courses",
            },
        ),
        migrations.AlterField(
            model_name="quota",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="machine_reservations",
                to="news.timeplace",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="machine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="make_queue.machine",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="quota",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="make_queue.quota",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
