# Generated by Django 3.2.8 on 2021-10-26 01:43

from datetime import datetime, timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_queue', '0023_machine_stream_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.utcfromtimestamp(0), verbose_name='last modified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machineusagerule',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.utcfromtimestamp(0), verbose_name='last modified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printer3dcourse',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.utcfromtimestamp(0), verbose_name='last modified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservationrule',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.utcfromtimestamp(0), verbose_name='last modified'),
            preserve_default=False,
        ),
    ]
