# Generated by Django 3.0.10 on 2020-09-20 01:52

from django.db import migrations
import multiselectfield.db.fields


def convert_start_days_from_bit_field_to_multiselect(apps, schema_editor):
    ReservationRule = apps.get_model("make_queue", "ReservationRule")
    for rule in ReservationRule.objects.all():
        start_days_bit_field = int(rule.start_days[0])

        start_days = []
        for shift in range(7):
            if start_days_bit_field & (1 << shift):
                start_days.append(shift + 1)  # the ISO weekdays are 1-indexed

        rule.start_days = start_days
        rule.save()


def convert_start_days_from_multiselect_to_bit_field(apps, schema_editor):
    ReservationRule = apps.get_model("make_queue", "ReservationRule")
    for rule in ReservationRule.objects.all():
        start_days = 0
        for day_iso_index in rule.start_days:
            day_bit_index = int(day_iso_index) - 1
            start_days |= 1 << day_bit_index

        rule.start_days = str(start_days)
        rule.save()


class Migration(migrations.Migration):
    dependencies = [
        (
            "make_queue",
            "0024_machine_and_machineusagerule_and_printer3dcourse_and_reservationrule_last_modified",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservationrule",
            name="start_days",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    (1, "Monday"),
                    (2, "Tuesday"),
                    (3, "Wednesday"),
                    (4, "Thursday"),
                    (5, "Friday"),
                    (6, "Saturday"),
                    (7, "Sunday"),
                ],
                max_length=13,
                verbose_name="start days for rule periods",
            ),
        ),
        migrations.RunPython(
            convert_start_days_from_bit_field_to_multiselect,
            convert_start_days_from_multiselect_to_bit_field,
        ),
    ]
