# Generated by Django 4.0.4 on 2022-04-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("make_queue", "0031_rename_printer3dcourse_advanced_course_to_raise3d_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="printer3dcourse",
            name="sla_course",
            field=models.BooleanField(default=False, verbose_name="SLA course"),
        ),
    ]
