# Generated by Django 4.2.9 on 2024-10-03 17:16

from django.db import migrations, models
import django.db.models.deletion
from make_queue.models.course import CoursePermission

def fill_temp_usage_requirement(apps, schema_editor):
    MachineType = apps.get_model('make_queue', 'MachineType')
    for machine_type in MachineType.objects.all():
        machine_type.usage_requirement_temp = machine_type.usage_requirement
        machine_type.save()


def create_default_permissions(apps, schema_editor):
    CoursePermission = apps.get_model('make_queue', 'CoursePermission')

    CoursePermission.objects.bulk_create([
        CoursePermission(name='User is authenticated', short_name='AUTH', description='Permission to reserve machines and workstations at MAKE NTNU'),
        CoursePermission(name='3D printer course', short_name='3DPR', description='Permission to use 3D printers at MAKE NTNU'),
        CoursePermission(name='Raise3D course', short_name='R3DP', description='Permission to use the Raise3D printer at MAKE NTNU'),
        CoursePermission(name='SLA course', short_name='SLAP', description='Permission to use the SLA printer at MAKE NTNU'),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('make_queue', '0034_alter_reservationrule_start_days'),
    ]    

    operations = [
        migrations.CreateModel(
            name='CoursePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=4, verbose_name='short name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
            ],
        ),
        migrations.AddField(
            model_name='printer3dcourse',
            name='course_permissions',
            field=models.ManyToManyField(blank=True, to='make_queue.coursepermission', verbose_name='course permissions'),
        ),
        migrations.AddField(
            model_name='machinetype',
            name='usage_requirement_temp',
            field=models.CharField(blank=True, max_length=4, verbose_name='usage requirement'),
        ),
        migrations.RunPython(
            code=fill_temp_usage_requirement,
        ),

        migrations.RunPython(
            code=create_default_permissions,
        ),




    ]
