# Generated by Django 4.2.9 on 2024-10-10 18:18

from django.db import migrations, models, transaction
import django.db.models.deletion

def update_requirement_values(apps, schema_editor):
    print("Updating usage requirement values for MachineType")
    CoursePermission = apps.get_model('make_queue', 'CoursePermission')
    Printer3DCourse = apps.get_model('make_queue', 'Printer3DCourse')
    MachineType = apps.get_model('make_queue', 'MachineType')

    for course in Printer3DCourse.objects.all():
        printer_course_id = 2
        raise3d_course_id = 3
        sla_course_id = 4

        permissions_to_set = [printer_course_id] 

        if getattr(course, 'raise3d_course', False):
            permissions_to_set.append(raise3d_course_id)
        if getattr(course, 'sla_course', False):
            permissions_to_set.append(sla_course_id)

        course.course_permissions.set(permissions_to_set)
        course.save()
        print(f"Updated course permissions for {course.name} to {course.course_permissions.all()}")

    for machine_type in MachineType.objects.all():
        if machine_type.usage_requirement_temp:
            course_permission = CoursePermission.objects.get(short_name=machine_type.usage_requirement_temp)
            machine_type.usage_requirement = course_permission
            machine_type.save()
            print(f"Updated usage requirement for {machine_type.name} to {course_permission}")

class Migration(migrations.Migration):

    dependencies = [
        ('make_queue', '0035_coursepermission_printer3dcourse_course_permissions_and_more'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='machinetype',
            name='usage_requirement',
        ),
        migrations.AddField(
            model_name='machinetype',
            name='usage_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='make_queue.CoursePermission', verbose_name='usage requirement'),   
        ),
        migrations.RunPython(
            code=update_requirement_values,
        ),
        migrations.RemoveField(
            model_name='machinetype',
            name='usage_requirement_temp',
        ),
        migrations.RemoveField(
            model_name='printer3dcourse',
            name='raise3d_course',
        ),
        migrations.RemoveField(
            model_name='printer3dcourse',
            name='sla_course',
        ),


    ]
