# Generated by Django 5.0.2 on 2026-08-31 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import card.modelfields


class Migration(migrations.Migration):
    dependencies = [
        (
            "make_queue",
            "0035_coursepermission_printer3dcourse_course_permissions_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseRegistrationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_number",
                    card.modelfields.CardNumberField(
                        blank=True,
                        error_messages={"unique": "Card number already in use"},
                        max_length=10,
                        null=True,
                        verbose_name="card number",
                    ),
                ),
                ("course_date", models.DateField(verbose_name="course date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Awaiting approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "submitted",
                    models.DateTimeField(auto_now_add=True, verbose_name="submitted"),
                ),
                (
                    "last_modified",
                    models.DateTimeField(auto_now=True, verbose_name="last modified"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_registration_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "course registration request",
                "verbose_name_plural": "course registration requests",
                "ordering": ("submitted",),
            },
        ),
        migrations.AddConstraint(
            model_name="courseregistrationrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("user",),
                name="courseregistrationrequest_at_most_one_pending_request_per_user",
            ),
        ),
    ]
