# Generated by Django 5.0.2 on 2026-03-24 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "make_queue",
            "0035_coursepermission_printer3dcourse_course_permissions_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursepermission",
            name="short_name",
            field=models.CharField(
                blank=True, max_length=4, unique=True, verbose_name="short name"
            ),
        ),
        migrations.AlterField(
            model_name="machinetype",
            name="usage_requirement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="make_queue.coursepermission",
                verbose_name="usage requirement",
            ),
        ),
    ]
