# Generated by Django 5.0.2 on 2026-08-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("make_queue", "0036_courseregistrationrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseRegistrationConfirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500, verbose_name="text")),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Only the active statements have to be confirmed.",
                        verbose_name="active",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="The statements are sorted ascending by this value.",
                        verbose_name="priority",
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(auto_now=True, verbose_name="last modified"),
                ),
            ],
            options={
                "verbose_name": "course registration confirmation",
                "verbose_name_plural": "course registration confirmations",
                "ordering": ("priority", "pk"),
            },
        ),
        migrations.AddField(
            model_name="courseregistrationrequest",
            name="confirmations",
            field=models.ManyToManyField(
                blank=True,
                related_name="registration_requests",
                to="make_queue.courseregistrationconfirmation",
                verbose_name="confirmations",
            ),
        ),
    ]
