# Generated by Django 2.2.8 on 2019-12-16 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("docs", "0003_user_association"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="current_content",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="in_use",
                to="docs.Content",
            ),
        ),
    ]
