# Generated by Django 3.1.4 on 2021-04-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_page_current_content_onetoone_and_related_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='changed',
            new_name='last_modified',
        ),
        migrations.AlterField(
            model_name='content',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='last modified'),
        ),
    ]
