# Generated by Django 2.0.9 on 2018-10-13 12:18

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0009_auto_20180503_0141"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsbase",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
