# Generated by Django 3.1.2 on 2020-10-30 00:10

from django.db import migrations
import web.modelfields
import web.multilingual.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_use_datetime_instead_of_date_and_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsbase',
            name='clickbait',
            field=web.multilingual.modelfields.MultiLingualTextField(verbose_name='clickbait'),
        ),
        migrations.AlterField(
            model_name='newsbase',
            name='title',
            field=web.multilingual.modelfields.MultiLingualTextField(verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='timeplace',
            name='place',
            field=web.modelfields.UnlimitedCharField(blank=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='timeplace',
            name='place_url',
            field=web.modelfields.URLTextField(blank=True, verbose_name='location URL'),
        ),
    ]
