# Generated by Django 4.0 on 2021-12-16 12:58

from django.db import migrations
import web.multilingual.modelfields
from web.multilingual.data_structures import MultiLingualTextStructure


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_article_and_event_and_timeplace_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_description',
            field=web.multilingual.modelfields.MultiLingualTextField(default=MultiLingualTextStructure('', use_default_for_empty=True), help_text='This should be a concise visual description of the image, which is mainly useful for people using a screen reader.', verbose_name='image description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='image_description',
            field=web.multilingual.modelfields.MultiLingualTextField(default=MultiLingualTextStructure('', use_default_for_empty=True), help_text='This should be a concise visual description of the image, which is mainly useful for people using a screen reader.', verbose_name='image description'),
            preserve_default=False,
        ),
    ]
