# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-16 13:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalty3D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField(auto_now_add=True)),
                ('removed_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Printer3D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('R', 'Reserved'), ('F', 'Free'), ('I', 'In use'), ('O', 'Out of order'), ('M', 'Maintenance')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Quota3D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_print', models.BooleanField(default=False)),
                ('max_time_reservation', models.FloatField(default=0)),
                ('max_number_of_reservations', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation3D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('event', models.BooleanField(default=False)),
                ('showed', models.NullBooleanField(default=None)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='make_queue.Printer3D')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='penalty3d',
            name='user_quota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='make_queue.Quota3D'),
        ),
    ]
