# Generated by Django 2.0.4 on 2018-04-06 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('make_queue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation3d',
            options={'permissions': (('can_view_reservation_user', 'Can view reservation user'),)},
        ),
        migrations.AlterModelOptions(
            name='reservationsewing',
            options={'permissions': (('can_view_reservation_user', 'Can view reservation user'),)},
        ),
    ]
