# Generated by Django 2.0 on 2018-01-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_queue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='location_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
