# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-17 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_queue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quota3d',
            options={'permissions': (('can_create_event_reservation', 'Can create event reservation'),)},
        ),
        migrations.AlterField(
            model_name='printer3d',
            name='status',
            field=models.CharField(choices=[('R', 'Reserved'), ('NS', 'Free, no show'), ('F', 'Free'), ('I', 'In use'), ('O', 'Out of order'), ('M', 'Maintenance')], max_length=2),
        ),
    ]
