# Generated by Django 2.0 on 2018-01-16 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('make_queue', '0002_machine_location_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation3d',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='reservationsewing',
            name='event_name',
        ),
        migrations.AlterField(
            model_name='reservation3d',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Event'),
        ),
        migrations.AlterField(
            model_name='reservationsewing',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Event'),
        ),
    ]
