# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-22 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('make_queue', '0002_auto_20171122_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation3d',
            name='event_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='reservationsewing',
            name='event_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='reservation3d',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='make_queue.Printer3D'),
        ),
        migrations.AlterField(
            model_name='reservationsewing',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='make_queue.SewingMachine'),
        ),
    ]
