# Generated by Django 2.0 on 2018-02-16 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('make_queue', '0003_auto_20180116_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quota',
            options={'permissions': (('can_create_event_reservation', 'Can create event reservation'), ('can_edit_quota', 'Can edit quotas'))},
        ),
    ]
