# Generated by Django 2.1.2 on 2018-10-25 12:25

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import make_queue.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('make_queue', '0007_auto_20180914_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineUsageRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_type', make_queue.fields.MachineTypeField(choices=[(1, '3D-printer'), (2, 'Symaskin')], unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='Printer3DCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('date', models.DateField()),
                ('card_number', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=256)),
                ('registered', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='reservationrule',
            name='machine_type',
            field=make_queue.fields.MachineTypeField(choices=[(1, '3D-printer'), (2, 'Symaskin')], verbose_name='Machine type'),
        ),
    ]
