# Generated by Django 2.1.2 on 2018-10-27 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('make_queue', '0008_auto_20181025_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printer3dcourse',
            name='registered',
        ),
        migrations.AddField(
            model_name='printer3dcourse',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('sent', 'Sent to Byggsikring'), ('access', 'Access granted')], default='registered', max_length=20),
        ),
        migrations.AlterField(
            model_name='quota',
            name='all',
            field=models.BooleanField(default=False, verbose_name='All users'),
        ),
        migrations.AlterField(
            model_name='quota',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
