# Generated by Django 2.1 on 2018-10-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_queue', '0008_printer3dcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printer3dcourse',
            name='email',
        ),
        migrations.AddField(
            model_name='printer3dcourse',
            name='registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='printer3dcourse',
            name='username',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
