# Generated by Django 2.1.5 on 2019-03-02 21:10

from django.db import migrations
import make_queue.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('make_queue', '0009_auto_20190213_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer3dcourse',
            name='username',
            field=make_queue.models.fields.UsernameField(max_length=32, unique=True, verbose_name='Username'),
        ),
    ]
