# Generated by Django 2.1 on 2018-10-05 06:36

from django.db import migrations
import make_queue.fields


class Migration(migrations.Migration):

    dependencies = [
        ('make_queue', '0009_auto_20181002_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationrule',
            name='machine_type',
            field=make_queue.fields.MachineTypeField(choices=[(1, '3D-printer'), (2, 'Symaskin')], verbose_name='Machine type'),
        ),
    ]
