# Generated by Django 2.1.2 on 2018-10-29 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('make_queue', '0009_auto_20181027_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer3dcourse',
            name='card_number',
            field=models.IntegerField(null=True, verbose_name='Card number (EM)'),
        ),
        migrations.AlterField(
            model_name='printer3dcourse',
            name='date',
            field=models.DateField(verbose_name='Course date'),
        ),
        migrations.AlterField(
            model_name='printer3dcourse',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='printer3dcourse',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('sent', 'Sent to Byggsikring'), ('access', 'Access granted')], default='registered', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='printer3dcourse',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='printer3dcourse',
            name='username',
            field=models.CharField(max_length=32, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='special_text',
            field=models.CharField(max_length=64),
        ),
    ]
