# Generated by Django 2.1.2 on 2018-11-01 16:48

from django.db import migrations
import make_queue.models.course


class Migration(migrations.Migration):

    dependencies = [
        ('make_queue', '0010_auto_20181029_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer3dcourse',
            name='username',
            field=make_queue.models.course.UsernameField(max_length=32, verbose_name='Username'),
        ),
    ]
