# Generated by Django 2.2.7 on 2019-12-23 15:27

from django.db import migrations, models


def set_out_of_order(apps, schema_editor):
    Machine = apps.get_model('make_queue', 'Machine')
    db_alias = schema_editor.connection.alias

    for machine in Machine.objects.using(db_alias).filter(status="O"):
        machine.out_of_order = True
        machine.save(using=db_alias)


def reverse_set_out_of_order(apps, schema_editor):
    Machine = apps.get_model('make_queue', 'Machine')
    db_alias = schema_editor.connection.alias

    for machine in Machine.objects.using(db_alias).filter(out_of_order=True):
        machine.status = "O"
        machine.save(using=db_alias)


class Migration(migrations.Migration):
    dependencies = [
        ('make_queue', '0012_usage_rules_multilingual_content_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='out_of_order',
            field=models.BooleanField(default=False, verbose_name='Out of order'),
        ),
        migrations.RunPython(set_out_of_order, reverse_set_out_of_order),
        migrations.RemoveField(
            model_name='machine',
            name='status',
        ),
        migrations.AddField(
            model_name='reservation',
            name='maintenance',
            field=models.BooleanField(default=False, verbose_name='Maintenance'),
        ),
    ]
