# Generated by Django 2.2.5 on 2019-10-08 17:46

import card.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('make_queue', '0012_usage_rules_multilingual_content_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer3dcourse',
            name='card_number',
            field=card.models.CardNumberField(null=True, unique=True, validators=[django.core.validators.MaxValueValidator(9999999999, 'Card number must be ten digits long'), django.core.validators.MinValueValidator(1000000, 'Card number must be ten digits long')]),
        ),
    ]
