# Generated by Django 2.2.5 on 2019-10-09 18:38

import card.models
import django.core.validators
from django.db import migrations, models


def to_cardnumberfield(apps, schema_editor):
    Printer3DCourse = apps.get_model('make_queue', 'Printer3DCourse')
    db_alias = schema_editor.connection.alias

    for registration in Printer3DCourse.objects.using(db_alias).all():
        if registration.old_card_number:
            registration.card_number = str(registration.old_card_number).zfill(10)
            registration.save()


def to_integerfield(apps, schema_editor):
    Printer3DCourse = apps.get_model('make_queue', 'Printer3DCourse')
    db_alias = schema_editor.connection.alias

    for registration in Printer3DCourse.objects.using(db_alias).all():
        if registration.card_number:
            registration.old_card_number = int(registration.card_number)
            registration.save()


class Migration(migrations.Migration):
    dependencies = [
        ('make_queue', '0012_usage_rules_multilingual_content_field'),
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(  # Rename database column for use when converting
            model_name='printer3dcourse',
            name='card_number',
            field=models.IntegerField(null=True, verbose_name='Card number (EM)', db_column='old_card_number')
        ),
        migrations.RenameField(  # Rename so card_number is available for replacement
            model_name='printer3dcourse',
            old_name='card_number',
            new_name='old_card_number'
        ),
        migrations.AddField(
            model_name='printer3dcourse',
            name='card_number',
            field=card.models.CardNumberField(max_length=10, null=True, unique=True, validators=[
                django.core.validators.RegexValidator('\\d{10}', 'Card number must be ten digits long')],
                                              verbose_name='Card number'),
        ),
        migrations.RunPython(to_cardnumberfield, to_integerfield),
        migrations.RemoveField(  # Remove old field when converting is done
            model_name='printer3dcourse',
            name='old_card_number'
        )
    ]
