# Generated by Django 2.2.7 on 2020-02-17 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('make_queue', '0013_course_card_number_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printer3dcourse',
            options={'permissions': (('can_send_access_control_mail', 'Can send access control mail'),)},
        ),
    ]
