# Generated by Django 2.2.5 on 2019-10-13 17:31

from django.db import migrations, models
import django.db.models.expressions


def add_cards(apps, schema_editor):
    """
    Connect card objects to course registration
    """
    Card = apps.get_model('card', 'Card')
    Printer3DCourse = apps.get_model('make_queue', 'Printer3DCourse')
    db_alias = schema_editor.connection.alias

    for registration in Printer3DCourse.objects.using(db_alias).all():
        if hasattr(registration, 'user') and registration.user:
            user = registration.user
            if hasattr(user, "card"):
                registration.card = user.card
                registration.save(using=db_alias)
        else:
            number = str(registration.card_number).zfill(10) if registration.card_number else None
            registration.card = Card.objects.using(db_alias).create(number=number)


def reverse_add_cards(apps, schema_editor):
    """
    Set course card_number from course card
    """
    Printer3DCourse = apps.get_model('make_queue', 'Printer3DCourse')
    db_alias = schema_editor.connection.alias

    for registration in Printer3DCourse.objects.using(db_alias).filter(card__isnull=False):
        registration.card_number = registration.card.number
        registration.save(using=db_alias)

    Printer3DCourse.objects.using(db_alias).filter(card__isnull=True).update(card_number=None)


class Migration(migrations.Migration):
    dependencies = [
        ('card', '0002_card_nullable_fields'),
        ('make_queue', '0013_course_card_number_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer3dcourse',
            name='card',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='card.Card'),
        ),
        migrations.RunPython(add_cards, reverse_add_cards),
        migrations.RemoveField(
            model_name='printer3dcourse',
            name='card_number',
        ),
    ]
