# Generated by Django 3.0.10 on 2020-11-09 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_queue', '0016_auto_20201107_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='stream_name',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Stream Name'),
        ),
    ]
