# Generated by Django 3.0.5 on 2020-09-13 01:30

import card.modelfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import make_queue.models.fields
import web.modelfields
import web.multilingual.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('make_queue', '0016_auto_20201103_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='location',
            field=web.modelfields.UnlimitedCharField(verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='location_url',
            field=web.modelfields.URLTextField(verbose_name='Location URL'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_model',
            field=web.modelfields.UnlimitedCharField(verbose_name='Machine model'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=web.modelfields.UnlimitedCharField(unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='printer3dcourse',
            name='_card_number',
            field=card.modelfields.CardNumberField(blank=True, default='', error_messages={'unique': 'Card number already in use'}, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Card number must be ten digits long.')], verbose_name='Card number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='printer3dcourse',
            name='name',
            field=models.CharField(blank=True, max_length=256, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='printer3dcourse',
            name='username',
            field=make_queue.models.fields.UsernameField(blank=True, max_length=32, unique=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='quota',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='quota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='make_queue.Quota'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='special_text',
            field=web.modelfields.UnlimitedCharField(blank=True),
        ),
    ]
