# Generated by Django 3.1.3 on 2021-03-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_queue', '0016_auto_20201103_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer3dcourse',
            name='advanced_course',
            field=models.BooleanField(default=False, null=True, verbose_name='Advanced course'),
        ),
        migrations.AlterField(
            model_name='machinetype',
            name='usage_requirement',
            field=models.CharField(choices=[('AUTH', 'Only has to be logged in'), ('3DPR', 'Taken the 3D printer course'), ('A3DPR', 'Taken the advanced 3D printer course')], default='AUTH', max_length=5, verbose_name='Usage requirement'),
        ),
    ]
