# Generated by Django 3.1.6 on 2021-04-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_queue', '0019_add_related_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationrule',
            name='max_inside_border_crossed',
            field=models.FloatField(verbose_name='Hours multiperiod'),
        ),
    ]
