# Generated by Django 3.0.10 on 2020-11-09 23:55

from django.db import migrations, models
from django.core.validators import RegexValidator

def set_stream_name(apps, schema_editor):
    Machine = apps.get_model('make_queue', 'Machine')
    db_alias = schema_editor.connection.alias

    for machine in Machine.objects.using(db_alias).filter(machine_type__has_stream=True):
        machine.stream_name = machine.name.replace("ö", "o").replace(" ", "-")
        machine.save()

class Migration(migrations.Migration):

    dependencies = [
        ('make_queue', '0021_alter_id_fields_to_use_bigautofield'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='stream_name',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, validators=[RegexValidator(code='NOT_URL_SAFE', message='Stream name can only consist of english letters, numbers, hyphens or underscores.', regex='^[a-zA-Z0-9_-]+$')], verbose_name='Stream Name'),
        ),
        migrations.RunPython(set_stream_name, migrations.RunPython.noop),
    ]
