# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 08:37
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Tittel')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
