# Generated by Django 2.0.1 on 2018-10-09 17:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentbox', '0002_auto_20180412_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentbox',
            name='content_en',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
