# Generated by Django 2.0.9 on 2018-10-13 12:18

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentbox', '0002_auto_20180412_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentbox',
            options={'permissions': (('can_upload_image', 'Can upload image for CKEditor'), ('can_browse_image', 'Can brows image in CKEditor'))},
        ),
        migrations.AlterField(
            model_name='contentbox',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
