# Generated by Django 2.1.2 on 2018-12-09 17:36
import json
from django.db import migrations
import web.multilingual.modelfields


def merge_content_box_fields(apps, schema_editor):
    ContentBox = apps.get_model("contentbox", "ContentBox")
    for content_box in ContentBox.objects.all():
        content_box.content = json.dumps({
            "nb": content_box.content,
            "en": content_box.content_en,
        })
        content_box.save()


def reverse_merge_content_box_fields(apps, schema_editor):
    ContentBox = apps.get_model("contentbox", "ContentBox")
    for content_box in ContentBox.objects.all():
        content_dict = json.loads(content_box.content)
        content_box.content = content_dict["nb"]
        content_box.content_en = content_dict["en"]
        content_box.save()


class Migration(migrations.Migration):

    dependencies = [
        ('contentbox', '0004_contentbox_content_en'),
    ]

    operations = [
        migrations.RunPython(merge_content_box_fields, reverse_merge_content_box_fields),
        migrations.RemoveField(
            model_name='contentbox',
            name='content_en',
        ),
        migrations.AlterField(
            model_name='contentbox',
            name='content',
            field=web.multilingual.modelfields.MultiLingualRichTextUploadingField(),
        ),
    ]
