# Generated by Django 4.0.1 on 2022-01-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentbox', '0008_contentbox_last_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentbox',
            old_name='title',
            new_name='url_name',
        ),
        migrations.AlterField(
            model_name='contentbox',
            name='url_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='URL name'),
        ),
    ]
