# Generated by Django 4.0.1 on 2022-01-11 19:54

from django.db import migrations
import web.multilingual.modelfields
from web.multilingual.data_structures import MultiLingualTextStructure


class Migration(migrations.Migration):

    dependencies = [
        ('contentbox', '0009_rename_title_contentbox_url_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentbox',
            name='title',
            field=web.multilingual.modelfields.MultiLingualTextField(default=MultiLingualTextStructure('', True), verbose_name='Title'),
            preserve_default=False,
        ),
    ]
