# Generated by Django 2.1.5 on 2019-03-03 13:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0004_auto_20181009_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(default='', max_length=32)),
                ('study_program', models.CharField(default='', max_length=32)),
                ('card_number', models.CharField(default='', max_length=32)),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('date_quit', models.DateField(blank=True, null=True)),
                ('reason_quit', models.TextField(default='', max_length=256)),
                ('comment', models.TextField(default='', max_length=256)),
                ('active', models.BooleanField(default=True)),
                ('guidance_exemption', models.BooleanField(default=False)),
                ('quit', models.BooleanField(default=False)),
                ('retired', models.BooleanField(default=False)),
                ('honorary_member', models.BooleanField(default=False)),
                ('committees', models.ManyToManyField(to='groups.Committee')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('is_internal', 'Is a member of MAKE NTNU'), ('can_register_new_member', 'Can register new member'), ('can_edit_group_membership', 'Can edit the groups a member is part of, including (de)activation')),
            },
        ),
        migrations.CreateModel(
            name='MemberProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Drive', 'drive'), ('Slack', 'slack'), ('Google Calendar', 'calendar'), ('Trello', 'trello'), ('Email lists', 'email'), ('Website', 'website')], max_length=32)),
                ('value', models.BooleanField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.Member')),
            ],
        ),
    ]
