# Generated by Django 2.1.5 on 2019-03-14 08:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='honorary_member',
        ),
        migrations.AddField(
            model_name='member',
            name='honorary',
            field=models.BooleanField(default=False, verbose_name='Honorary'),
        ),
        migrations.AlterField(
            model_name='member',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='member',
            name='card_number',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Card number (EM)'),
        ),
        migrations.AlterField(
            model_name='member',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=256, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='member',
            name='committees',
            field=models.ManyToManyField(blank=True, to='groups.Committee', verbose_name='Committees'),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date joined'),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_quit',
            field=models.DateField(blank=True, null=True, verbose_name='Date quit'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='member',
            name='guidance_exemption',
            field=models.BooleanField(default=False, verbose_name='Guidance exemption'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='member',
            name='quit',
            field=models.BooleanField(default=False, verbose_name='Has quit'),
        ),
        migrations.AlterField(
            model_name='member',
            name='reason_quit',
            field=models.TextField(blank=True, default='', max_length=256, verbose_name='Reason quit'),
        ),
        migrations.AlterField(
            model_name='member',
            name='retired',
            field=models.BooleanField(default=False, verbose_name='Retired'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(blank=True, max_length=64, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='member',
            name='study_program',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Study program'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
