# Generated by Django 2.2.4 on 2019-09-23 15:04

from django.db import migrations


def member_card(apps, schema_editor):
    """
    Set user card number from member card number
    """
    Member = apps.get_model('internal', 'Member')
    db_alias = schema_editor.connection.alias

    for member in Member.objects.using(db_alias).all():
        member.user.card_number = member.card_number
        member.user.save()


def reverse_member_card(apps, schema_editor):
    """
    Reverse setting of card number on user
    """
    Member = apps.get_model('internal', 'Member')
    db_alias = schema_editor.connection.alias

    for member in Member.objects.using(db_alias).all():
        card_number = member.user.card_number
        member.card_number = card_number if card_number else ""
        member.save()


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0004_member_phone_number_field'),
        ('users', '0003_user_card_number'),
    ]

    operations = [
        migrations.RunPython(member_card, reverse_member_card),
        migrations.RemoveField(
            model_name='member',
            name='card_number',
        ),
    ]
