# Generated by Django 2.2.4 on 2019-09-23 15:04

from django.db import migrations


def member_card(apps, schema_editor):
    """
    Create Card objects connecting the member card_number to the member user.
    """
    Card = apps.get_model('card', 'Card')
    Member = apps.get_model('internal', 'Member')
    db_alias = schema_editor.connection.alias

    for member in Member.objects.using(db_alias).all():
        if member.card_number:
            user = member.user
            if not hasattr(user, 'card'):
                # Create card without EM prefix
                Card.objects.using(db_alias).create(user=user, number=member.card_number.split("EM ")[-1].zfill(10))


def reverse_member_card(apps, schema_editor):
    """
    Reverse creation of Card objects from members
    """
    Card = apps.get_model('card', 'Card')
    Member = apps.get_model('internal', 'Member')
    db_alias = schema_editor.connection.alias

    for card in Card.objects.using(db_alias).all():
        member = Member.objects.using(db_alias).filter(user_id=card.user.id)
        if member.exists():
            member.update(card_number=str(card.number))


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0004_member_phone_number_field'),
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(member_card, reverse_member_card),
        migrations.RemoveField(
            model_name='member',
            name='card_number',
        ),
    ]
