# Generated by Django 3.0.10 on 2020-11-03 14:17

from django.db import migrations, models
import web.multilingual.database


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0005_remove_member_card_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', web.multilingual.database.MultiLingualTextField(max_length=100, unique=True, verbose_name='Title')),
                ('description', web.multilingual.database.MultiLingualRichTextUploadingField(verbose_name='Description')),
                ('date', models.DateField()),
            ],
        ),
    ]
