# Generated by Django 3.1.4 on 2021-01-07 12:46

from django.db import migrations, models


def set_status(apps, schema_editor):
    Member = apps.get_model('internal', 'Member')
    for member in Member.objects.all():
        if member.quit:
            status = 'Q'
            member.guidance_exemption = True
        elif member.retired:
            status = 'R'
            member.guidance_exemption = True
        elif not member.active:
            status = 'I'
            member.guidance_exemption = True
        else: 
            status = 'A'
            member.guidance_exemption = False

        member.status = status
        member.save()

def set_retired_active_quit(apps, schema_editor):
    Member = apps.get_model('internal', 'Member')
    for member in Member.objects.all():
        if member.status == 'Q':
            member.quit = True
            member.guidance_exemption = True
        elif member.status == 'R':
            member.retired = True
            member.guidance_exemption = True
        elif member.status == 'I':
            member.active = False
            member.guidance_exemption = True
        elif member.status == 'A':
            member.active = True
            member.guidance_exemption = False
        member.save()

class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0006_secret'),
    ]

    operations = [
         migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('Q', 'Quit'), ('R', 'Retired')], default='A', max_length=1),
        ),
        migrations.RunPython(set_status, set_retired_active_quit),
        migrations.RemoveField(
            model_name='member',
            name='active',
        ),
        migrations.RemoveField(
            model_name='member',
            name='quit',
        ),
        migrations.RemoveField(
            model_name='member',
            name='retired',
        ),
       
    ]
