# Generated by Django 3.1.4 on 2021-08-24 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0007_member_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidanceHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=9)),
                ('start_time', models.TimeField(blank=True)),
                ('end_time', models.TimeField(blank=True)),
                ('slot_four', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_four', to='internal.member', verbose_name='Slot four')),
                ('slot_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_one', to='internal.member', verbose_name='Slot one')),
                ('slot_three', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_three', to='internal.member', verbose_name='Slot three')),
                ('slot_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_two', to='internal.member', verbose_name='Slot two')),
            ],
            options={
                'verbose_name_plural': 'Guidance hours',
                'ordering': ('start_time',),
            },
        ),
    ]
