# Generated by Django 4.0.1 on 2022-01-30 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0015_member_gmail_and_MAKE_email_and_ntnu_starting_semester_and_github_and_discord_and_minecraft_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'permissions': (('is_internal', 'Is a member of MAKE NTNU'), ('can_edit_group_membership', 'Can edit the groups a member is part of, including (de)activation'), ('can_change_rich_text_source', "Can change rich text fields' HTML source code directly (including adding <script> tags)"))},
        ),
    ]
