# Generated by Django 4.0.2 on 2022-02-28 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import web.multilingual.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('internal', '0016_can_change_rich_text_source_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSecret',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', web.multilingual.modelfields.MultiLingualTextField(db_index=True, max_length=100, verbose_name='title')),
                ('content', web.multilingual.modelfields.MultiLingualRichTextUploadingField(verbose_name='description')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical secret',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
