# Generated by Django 4.0.3 on 2022-04-02 22:58

from datetime import date
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0018_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='date',
            field=models.DateField(default=date.fromtimestamp(0), verbose_name='date'),
            preserve_default=False,
        ),
    ]
