# Generated by Django 2.0.1 on 2018-10-16 17:08

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contentbox", "0003_auto_20181013_1418"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentbox",
            name="content_en",
            field=ckeditor_uploader.fields.RichTextUploadingField(default=""),
        ),
    ]
