services:
  web:
    platform: linux/amd64
    image: make_web
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    command: uv run manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      # The bottom-most envvars will override the ones above
      - ../.env
      - ../.env.docker
    volumes:
      # Mounts the parent folder (i.e. the repo folder) as a volume with the same path
      # as `PROJECT_DIR` in the Dockerfile, to enable hot reloading of changed local
      # files
      - ../:/web
      # Makes the files inside `STATIC_DATA_DIR` (see the Dockerfile) persistent
      - static-data:/vol/web

volumes:
  static-data:
