# Generated by Django 2.2.5 on 2019-10-18 17:41

from django.db import migrations

import card.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_rename_user_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="card_number",
            field=card.modelfields.CardNumberField(
                blank=True,
                error_messages={"unique": "Card number already in use"},
                max_length=10,
                null=True,
                unique=True,
                verbose_name="card number",
            ),
        ),
    ]
