# Generated by Django 2.2.8 on 2019-12-15 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(regex='^[0-9A-Za-z ():]+$', message='Only numbers, letters, spaces, parentheses and colons are allowed.')], verbose_name='title'),
        ),
    ]
