# Generated by Django 2.2.5 on 2019-10-13 17:25

import card.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='number',
            field=card.models.CardNumberField(error_messages={'unique': 'Card number already in use'}, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Card number must be ten digits long.')], verbose_name='Card number'),
        ),
        migrations.AlterField(
            model_name='card',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
