# Generated by Django 5.0.2 on 2026-05-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(max_length=255, unique=True, verbose_name="path"),
                ),
                ("count", models.PositiveIntegerField(default=0, verbose_name="count")),
                (
                    "last_visited",
                    models.DateTimeField(auto_now=True, verbose_name="last visited"),
                ),
            ],
            options={
                "verbose_name": "page view",
                "verbose_name_plural": "page views",
                "ordering": ["-count"],
            },
        ),
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="identifier",
                    ),
                ),
                (
                    "first_seen",
                    models.DateTimeField(auto_now_add=True, verbose_name="first seen"),
                ),
                (
                    "last_seen",
                    models.DateTimeField(auto_now=True, verbose_name="last seen"),
                ),
            ],
            options={
                "verbose_name": "visitor",
                "verbose_name_plural": "visitors",
            },
        ),
    ]
