# Generated by Django 2.2.5 on 2019-11-20 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('unit', models.CharField(blank=True, max_length=16, null=True)),
                ('description', models.TextField(blank=True, max_length=256)),
                ('comment', models.TextField(blank=True, max_length=256, null=True)),
                ('consumable', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to='inventory')),
                ('categories', models.ManyToManyField(related_name='items', to='inventory.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ItemInSubContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=1, max_digits=6)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_in_subcontainer', to='inventory.Item')),
            ],
            options={
                'verbose_name_plural': 'items in subcontainer',
            },
        ),
        migrations.CreateModel(
            name='SubContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontainers', to='inventory.Container')),
                ('items', models.ManyToManyField(related_name='subcontainers', through='inventory.ItemInSubContainer', to='inventory.Item')),
            ],
        ),
        migrations.AddField(
            model_name='iteminsubcontainer',
            name='subcontainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_in_subcontainer', to='inventory.SubContainer'),
        ),
        migrations.AddConstraint(
            model_name='subcontainer',
            constraint=models.UniqueConstraint(fields=('name', 'container'), name='unique_name_per_container'),
        ),
        migrations.AddConstraint(
            model_name='iteminsubcontainer',
            constraint=models.UniqueConstraint(fields=('item', 'subcontainer'), name='unique_item_and_subcontainer'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['name'], name='inventory_i_name_637656_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['description'], name='inventory_i_descrip_072d9d_idx'),
        ),
    ]
