# Generated by Django 2.1.7 on 2019-02-21 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_search_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='search_vector',
        ),
    ]
