# Generated by Django 2.1.7 on 2019-03-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20190221_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='comment',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='iteminsubcontainer',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
