# Generated by Django 2.1.7 on 2019-04-02 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_item_consumeable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='consumeable',
            new_name='consumable',
        ),
    ]
