# Generated by Django 2.2.5 on 2019-10-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20190402_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='comment',
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(max_length=256),
        ),
    ]
