# Generated by Django 2.2.5 on 2019-10-21 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20191021_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AlterField(
            model_name='container',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='inventory.Room'),
        ),
        migrations.AlterField(
            model_name='iteminsubcontainer',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iteminsubcontainers', to='inventory.Item'),
        ),
        migrations.AlterField(
            model_name='iteminsubcontainer',
            name='subcontainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iteminsubcontainers', to='inventory.SubContainer'),
        ),
        migrations.AlterField(
            model_name='subcontainer',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontainers', to='inventory.Container'),
        ),
        migrations.AlterField(
            model_name='subcontainer',
            name='items',
            field=models.ManyToManyField(related_name='subcontainers', through='inventory.ItemInSubContainer', to='inventory.Item'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('items', models.ManyToManyField(related_name='items', to='inventory.Item')),
            ],
        ),
    ]
