# Generated by Django 2.2.5 on 2019-10-28 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='room',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
