# Generated by Django 3.0.4 on 2020-03-14 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(choices=[('I', 'Information'), ('W', 'Warning'), ('E', 'Error')], default='I', max_length=1, verbose_name='Type')),
                ('site_wide', models.BooleanField(verbose_name='Site-wide')),
                ('content', models.CharField(max_length=256, verbose_name='Content')),
                ('link', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Link')),
                ('display_from', models.DateTimeField(default=datetime.datetime(2020, 3, 14, 10, 30, 37, 551531))),
                ('display_to', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
