# Generated by Django 3.0.11 on 2020-11-10 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_help_text_and_naming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='display_from',
            field=models.DateTimeField(default=django.utils.timezone.localtime, help_text='The date from which the announcement will be shown.', verbose_name='Display from'),
        ),
    ]
