# Generated by Django 3.0.4 on 2020-03-14 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_multilingual_content_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='classification',
            field=models.CharField(choices=[('I', 'Information'), ('W', 'Warning message'), ('E', 'Error message')], default='I', max_length=1, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='display_from',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 14, 13, 51, 34, 422662), verbose_name='Display from'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='display_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Display to'),
        ),
    ]
