# Generated by Django 3.1.2 on 2020-10-30 00:10

from django.db import migrations
import web.fields
import web.multilingual.database


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_use_timezone_aware_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=web.multilingual.database.MultiLingualTextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='link',
            field=web.fields.URLTextField(blank=True, help_text='An optional link to an information page.', verbose_name='Link'),
        ),
    ]
