# Generated by Django 2.1.7 on 2019-03-29 20:39

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("internal", "0003_member_property_to_system_access"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                default="",
                max_length=32,
                region=None,
                verbose_name="phone number",
            ),
        ),
    ]
