# Generated by Django 2.2.4 on 2019-09-23 15:04

from django.db import migrations


def update_user_card_from_member(apps, schema_editor):
    """
    Set user card number from member card number
    """
    Member = apps.get_model('internal', 'Member')
    db_alias = schema_editor.connection.alias

    for member in Member.objects.using(db_alias).all():
        if member.card_number and member.user:
            member.user.card_number = member.card_number
            member.user.save(using=db_alias)


def reverse_update_user_card_from_member(apps, schema_editor):
    """
    Reverse setting of card number on user
    """
    Member = apps.get_model('internal', 'Member')
    db_alias = schema_editor.connection.alias

    for member in Member.objects.using(db_alias).all():
        if member.user and member.user.card_number:
            member.card_number = member.user.card_number
            member.save(using=db_alias)


class Migration(migrations.Migration):
    dependencies = [
        ('internal', '0004_member_phone_number_field'),
        ('users', '0003_user_card_number'),
    ]

    operations = [
        migrations.RunPython(update_user_card_from_member, reverse_update_user_card_from_member),
        migrations.RemoveField(
            model_name='member',
            name='card_number',
        ),
    ]
