# Generated by Django 3.1.4 on 2021-03-26 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0013_rename_date_quit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='email',
            new_name='contact_email',
        ),
    ]
