# Generated by Django 4.1.7 on 2023-03-24 10:16

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("internal", "0024_historicalmember_and_historicalmember_committees"),
    ]

    operations = [
        migrations.AddField(
            model_name="secret",
            name="extra_view_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Extra permissions that are required for viewing the secret. If a user does not have all the chosen permissions, it will be hidden to them.",
                related_name="secrets_with_extra_view_perm",
                to="auth.permission",
                verbose_name="extra view permissions",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalSecret_extra_view_permissions",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="internal.historicalsecret",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="auth.permission",
                    ),
                ),
                (
                    "secret",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="internal.secret",
                    ),
                ),
            ],
            options={
                "verbose_name": "HistoricalSecret_extra_view_permissions",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
