# Generated by Django 4.2.9 on 2024-02-27 16:42

from django.db import migrations
import web.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0026_add_secret_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmember',
            name='discord_username',
            field=web.modelfields.UnlimitedCharField(blank=True, verbose_name='Discord username'),
        ),
        migrations.AlterField(
            model_name='member',
            name='discord_username',
            field=web.modelfields.UnlimitedCharField(blank=True, verbose_name='Discord username'),
        ),
    ]
