# Generated by Django 5.0.2 on 2026-01-22 17:52

from django.db import migrations, models
import datetime

schedule = {
    0: [ 
        (datetime.time(12, 15), datetime.time(14, 7)),
        (datetime.time(14, 7), datetime.time(16, 7)),
        (datetime.time(16, 7), datetime.time(18, 0)),
    ],
    1: [  
        (datetime.time(12, 15), datetime.time(14, 7)),
        (datetime.time(14, 7), datetime.time(16, 7)),
        (datetime.time(16, 7), datetime.time(18, 0)),
    ],
    2: [ 
        (datetime.time(12, 15), datetime.time(14, 7)),
        (datetime.time(14, 7), datetime.time(16, 7)),
        (datetime.time(16, 7), datetime.time(18, 0)),
    ],
    3: [ 
        (datetime.time(12, 15), datetime.time(14, 7)),
        (datetime.time(14, 7), datetime.time(16, 7)),
        (datetime.time(16, 7), datetime.time(18, 0)),
    ],
    4: [
        (datetime.time(12, 15), datetime.time(14, 7)),
        (datetime.time(14, 7), datetime.time(16, 0)),
    ],
}

def add_guidance_hours(apps, schema_editor):
    GuidanceHours = apps.get_model("internal", "GuidanceHours")

    for weekday in range(0, 5):
        for from_time, to_time in schedule[weekday]:
            GuidanceHours.objects.get_or_create(
                weekday=weekday,
                from_time=from_time,
                to_time=to_time,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0026_add_secret_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidanceHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday')], verbose_name='weekday')),
                ('from_time', models.TimeField(verbose_name='from time')),
                ('to_time', models.TimeField(verbose_name='to time')),
                ('members', models.ManyToManyField(related_name='guidance_hours', to='internal.member', verbose_name='members')),
            ],
        ),
        migrations.RunPython(add_guidance_hours, migrations.RunPython.noop),
    ]
