# Generated by Django 4.1.7 on 2023-11-17 16:00

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0026_add_secret_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='title')),
                ('slug', models.SlugField(unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(max_length=150000, verbose_name='text')),
            ],
            options={
                'verbose_name': 'lore article',
                'verbose_name_plural': 'lore articles',
            },
        ),
    ]
