# Generated by Django 4.1.7 on 2023-08-18 08:29

from django.db import migrations, models
import functools
import internal.models
import util.modelfields
import util.storage


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0026_add_secret_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('slug', models.SlugField()),
                ('text', models.TextField(verbose_name='text')),
                ('image', util.modelfields.CompressedImageField(blank=True, max_length=200, storage=util.storage.OverwriteStorage(), upload_to=functools.partial(util.storage.UploadToUtils._actual_upload_to, *(), **{'upload_to': internal.models.internal_subclass_directory_path}), verbose_name='image')),
            ],
            options={
                'verbose_name_plural': 'Lore articles',
            },
        ),
    ]
