# Generated by Django 4.2.9 on 2025-10-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0026_add_secret_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='date',
            new_name='time',
        ),
        migrations.AlterField(
            model_name='quote',
            name='time',
            field=models.DateTimeField(verbose_name='-time it was said'),
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ('-time',)},
        ),
    ]
