# Generated by Django 5.0.2 on 2026-08-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("internal", "0027_guidance_hour"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guidancehour",
            options={"ordering": ("weekday", "from_time")},
        ),
        migrations.AlterField(
            model_name="guidancehour",
            name="notes",
            field=models.TextField(blank=True, max_length=2000, verbose_name="notes"),
        ),
        migrations.AddConstraint(
            model_name="guidancehour",
            constraint=models.CheckConstraint(
                check=models.Q(("from_time__lt", models.F("to_time"))),
                name="guidance_hour_from_time_before_to_time",
            ),
        ),
        migrations.AddConstraint(
            model_name="guidancehour",
            constraint=models.UniqueConstraint(
                fields=("weekday", "from_time", "to_time"),
                name="guidance_hour_unique_weekday_time_range",
            ),
        ),
    ]
