# Generated by Django 4.1.7 on 2023-11-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0027_lore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lore',
            name='text',
            field=models.TextField(max_length=150000, verbose_name='text'),
        ),
    ]
