# Generated by Django 2.1.1 on 2018-10-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0003_auto_20180925_2204"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committee",
            name="clickbait",
            field=models.TextField(
                blank=True, max_length=300, verbose_name="clickbait"
            ),
        ),
        migrations.AlterField(
            model_name="committee",
            name="description",
            field=models.TextField(verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="committee",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="committee",
            name="image",
            field=models.ImageField(blank=True, upload_to="", verbose_name="image"),
        ),
    ]
