# Generated by Django 3.2.2 on 2021-05-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0005_remove_committee_clickbait_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committee",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
