# Generated by Django 3.2.8 on 2021-10-25 18:28

from datetime import datetime, timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0007_add_related_and_verbose_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="committee",
            name="last_modified",
            field=models.DateTimeField(
                auto_now=True,
                default=datetime.utcfromtimestamp(0),
                verbose_name="last modified",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inheritancegroup",
            name="last_modified",
            field=models.DateTimeField(
                auto_now=True,
                default=datetime.utcfromtimestamp(0),
                verbose_name="last modified",
            ),
            preserve_default=False,
        ),
    ]
