# Generated by Django 2.0.1 on 2018-05-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='card_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='kortnummer'),
        ),
    ]
