# Generated by Django 2.0.1 on 2018-04-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_checkin',
            field=models.DateTimeField(auto_now=True, verbose_name='Sist sjekket inn'),
        ),
    ]
