# Generated by Django 2.0.1 on 2018-02-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_auto_20180211_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Ferdighet'),
        ),
    ]
