# Generated by Django 2.0.1 on 2018-01-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_auto_20180118_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='\\shahzeb\\Desktop\\zoidberg.gif', upload_to='photos/%Y/%m/%d', verbose_name='Profilbilde'),
        ),
    ]
