# Generated by Django 2.0.2 on 2018-03-02 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_auto_20180221_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userskill',
            options={'ordering': ('skill__title',)},
        ),
    ]
