# Generated by Django 2.0.2 on 2018-08-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_auto_20180504_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='title_en',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Skill (english)'),
        ),
        migrations.AddField(
            model_name='suggestskill',
            name='title_en',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Suggested skill'),
        ),
    ]
