# Generated by Django 2.0.2 on 2018-09-06 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_auto_20180830_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suggestskill',
            options={'ordering': ('title',), 'permissions': (('can_force_suggestion', 'Can force suggestion'),)},
        ),
    ]
