# Generated by Django 2.0.1 on 2018-02-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_auto_20180211_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Ferdighet'),
        ),
    ]
