# Generated by Django 2.0.1 on 2018-01-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://pbs.twimg.com/profile_images/817411634113040385/x3omzI6x.jpg', upload_to='photos/%Y/%m/%d', verbose_name='Profilbilde'),
        ),
    ]
