# Generated by Django 2.0.2 on 2018-03-07 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkin', '0004_suggestskill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suggestskill',
            options={'ordering': ('title',)},
        ),
        migrations.AddField(
            model_name='suggestskill',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkin.Profile'),
        ),
        migrations.RemoveField(
            model_name='suggestskill',
            name='voters',
        ),
        migrations.AddField(
            model_name='suggestskill',
            name='voters',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
