# Generated by Django 2.0.1 on 2018-01-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0005_auto_20180119_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='checked_in',
            field=models.BooleanField(default=False, verbose_name='Innsjekkingsstatus'),
        ),
    ]
