# Generated by Django 2.0.2 on 2018-03-07 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0005_auto_20180307_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestskill',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='suggestskill',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='checkin.Profile'),
        ),
        migrations.AlterField(
            model_name='suggestskill',
            name='voters',
            field=models.ManyToManyField(related_name='votes', to='checkin.Profile'),
        ),
    ]
