# Generated by Django 2.2.4 on 2019-09-22 17:28

from django.db import migrations


def create_cards_from_profiles(apps, schema_editor):
    """
    Create Card objects connecting the profile card_id to the profile user
    """
    Card = apps.get_model('card', 'Card')
    Profile = apps.get_model('checkin', 'Profile')
    db_alias = schema_editor.connection.alias

    for profile in Profile.objects.using(db_alias).all():
        if profile.card_id:
            user = profile.user
            if not hasattr(user, 'card'):
                Card.objects.using(db_alias).create(user=user, number=profile.card_id)


def reverse_create_cards_from_profiles(apps, schema_editor):
    """
    Reverse creation of Card objects from profiles
    """
    Card = apps.get_model('card', 'Card')
    Profile = apps.get_model('checkin', 'Profile')
    db_alias = schema_editor.connection.alias

    for card in Card.objects.using(db_alias).all():
        profile = Profile.objects.using(db_alias).filter(user_id=card.user.id)
        if profile.exists():
            profile.update(card_id=card.number)


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0006_auto_20180906_1915'),
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_cards_from_profiles, reverse_create_cards_from_profiles),
        migrations.RemoveField(
            model_name='profile',
            name='card_id',
        ),
    ]
