# Generated by Django 2.2.4 on 2019-09-22 17:28

from django.db import migrations


def create_cards_from_profiles(apps, schema_editor):
    """
    Set user card_number from  profile card_id
    """
    Profile = apps.get_model('checkin', 'Profile')
    db_alias = schema_editor.connection.alias

    for profile in Profile.objects.using(db_alias).all():
        if profile.user:
            profile.user.card_number = profile.card_id
            profile.user.save(using=db_alias)


def reverse_create_cards_from_profiles(apps, schema_editor):
    """
    Reverse setting of user card_number
    """
    Profile = apps.get_model('checkin', 'Profile')
    db_alias = schema_editor.connection.alias

    for profile in Profile.objects.using(db_alias).all():
        if profile.user:
            profile.card_id = profile.user.card_number
            profile.save(using=db_alias)


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0006_auto_20180906_1915'),
        ('users', '0003_user_card_number'),
    ]

    operations = [
        migrations.RunPython(create_cards_from_profiles, reverse_create_cards_from_profiles),
        migrations.RemoveField(
            model_name='profile',
            name='card_id',
        ),
    ]
