# Generated by Django 2.0.1 on 2018-01-21 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0006_profile_checked_in'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='checked_in',
            new_name='on_make',
        ),
    ]
