# Generated by Django 2.0.1 on 2018-04-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0007_auto_20180307_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_checkin',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
