# Generated by Django 2.0.2 on 2018-04-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0008_profile_last_checkin'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=100, verbose_name='Kortnummer')),
                ('last_scan', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
