# Generated by Django 2.0.2 on 2018-04-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0009_registerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerprofile',
            name='last_scan',
            field=models.DateTimeField(),
        ),
    ]
