# Generated by Django 3.1.3 on 2021-01-25 15:10

from django.db import migrations, models
import web.multilingual.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    web.multilingual.modelfields.MultiLingualTextField(
                        unique=True, verbose_name="category"
                    ),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    web.multilingual.modelfields.MultiLingualTextField(
                        unique=True, verbose_name="question"
                    ),
                ),
                (
                    "answer",
                    web.multilingual.modelfields.MultiLingualRichTextUploadingField(
                        verbose_name="answer"
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="questions",
                        to="faq.Category",
                        verbose_name="categories",
                    ),
                ),
            ],
            options={
                "verbose_name": "question",
                "verbose_name_plural": "questions",
            },
        ),
    ]
