# Generated by Django 4.0.4 on 2022-05-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faq", "0004_historicalquestion"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalquestion",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical question",
                "verbose_name_plural": "historical questions",
            },
        ),
        migrations.AlterField(
            model_name="historicalquestion",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
