# Generated by Django 2.2.5 on 2019-10-16 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makerspace', '0003_auto_20190226_1847'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tool',
            new_name='MakerSpace',
        ),
    ]
