# Generated by Django 3.1.2 on 2020-10-24 22:17

from django.db import migrations
import web.multilingual.database


class Migration(migrations.Migration):

    dependencies = [
        ('makerspace', '0003_equipment_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='title',
            field=web.multilingual.database.MultiLingualTextField(unique=True, verbose_name='Title'),
        ),
    ]
