# Generated by Django 2.2.5 on 2019-10-23 15:07

from django.db import migrations, models
import web.multilingual.database


class Migration(migrations.Migration):

    dependencies = [
        ('makerspace', '0004_auto_20191016_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', web.multilingual.database.MultiLingualTextField(max_length=100, verbose_name='Title')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Image')),
                ('content', web.multilingual.database.MultiLingualRichTextUploadingField()),
            ],
        ),
    ]
