# Generated by Django 2.2.5 on 2019-10-23 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makerspace', '0006_musician'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Musician',
        ),
    ]
