# Generated by Django 4.0.1 on 2022-01-20 19:12

from django.conf import settings
from django.db import migrations, models
import functools
from pathlib import Path
import util.storage


def move_equipment_images(apps, schema_editor):
    Equipment = apps.get_model('makerspace', 'Equipment')
    image_field = Equipment._meta.get_field('image')
    old_paths_renamed_to_new_paths = {}
    try:
        for equipment in Equipment.objects.all():
            if not equipment.image:
                continue

            old_name = equipment.image.name
            new_name = image_field.upload_to(equipment, Path(old_name).name)
            if new_name == old_name:
                continue
            else:
                # Ensure that the name is available
                new_name = image_field.storage.get_available_name(new_name, max_length=image_field.max_length)
            old_path = equipment.image.path
            new_path = settings.MEDIA_ROOT / new_name
            new_upload_dir = new_path.parent

            new_upload_dir.mkdir(mode=0o755, parents=True, exist_ok=True)
            try:
                Path(old_path).rename(new_path)
            except FileNotFoundError as e:
                raise RuntimeError(
                    f"Unable to find and rename image file of equipment with pk={equipment.pk}."
                    f" Consider clearing the image field."
                ) from e
            else:
                old_paths_renamed_to_new_paths[old_path] = new_path
            equipment.image.name = new_name
            equipment.save(update_fields=['image'])
    except Exception as e:
        for old_path, new_path in old_paths_renamed_to_new_paths.items():
            try:
                Path(new_path).rename(old_path)
            except Exception as e2:
                print("Exception while undoing renaming:\n", e2)
        raise e


class Migration(migrations.Migration):

    dependencies = [
        ('makerspace', '0006_equipment_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.ImageField(max_length=200, storage=util.storage.OverwriteStorage(), upload_to=functools.partial(util.storage.UploadToUtils._actual_upload_to, *(), **{'upload_to': 'equipment'}), verbose_name='Image'),
        ),
        migrations.RunPython(move_equipment_images, migrations.RunPython.noop),
    ]
