# Generated by Django 2.2.5 on 2019-10-23 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makerspace', '0007_delete_musician'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tools',
            new_name='Tool',
        ),
    ]
