# Generated by Django 2.2.5 on 2019-11-13 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makerspace', '0008_auto_20191023_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makerspace',
            name='image',
        ),
    ]
