# Generated by Django 2.1.5 on 2019-02-26 17:47

from django.db import migrations
import web.multilingual.database


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_auto_20181004_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='content',
            field=web.multilingual.database.MultiLingualRichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='tool',
            name='title',
            field=web.multilingual.database.MultiLingualTextField(max_length=100, verbose_name='Title'),
        ),
    ]
