name: Add pull requests to project

on:
  pull_request:
    types: [ opened, reopened, ready_for_review ]

jobs:
  add_to_project:
    # Don't run the job if it's a draft PR
    if: ${{ !github.event.pull_request.draft }}
    uses: ./.github/workflows/_reusable_add-content-to-project.yml
    with:
      content_id: ${{ github.event.pull_request.node_id }}
      status_field_value_name: "Ready for Review"
    secrets: inherit
