name: Add issues to project

on:
  issues:
    types: [ opened, reopened ]

jobs:
  add_to_project:
    uses: ./.github/workflows/_reusable_add-content-to-project.yml
    with:
      content_id: ${{ github.event.issue.node_id }}
      status_field_value_name: "TODO"
    secrets: inherit
