name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/cache@v1
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install system dependencies
        run: |
          sudo apt install python-dev libldap2-dev libsasl2-dev libssl-dev

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_codecov.txt

      - name: Run django tests
        run: |
          python manage.py collectstatic --no-input
          coverage run manage.py test

      - name: Upload to codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./.coverage
          token: ${{ secrets.CODECOV_TOKEN }}
