name: build

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.8, 3.9, "3.10" ]

    steps:
      - uses: actions/checkout@v2.3.5

      - uses: actions/cache@v2.1.7
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install System Dependencies
        run: |
          sudo apt update && sudo apt install python-dev libldap2-dev libsasl2-dev libssl-dev

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_codecov.txt

      - name: Run Django Tests
        run: |
          python manage.py collectstatic --no-input
          coverage run manage.py test
          coverage xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
